[build.environment]
  NODE_VERSION = "22"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "http://wwwinstagram.netlify.app/*"
  to = "https://wwwinstagram.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/video.html"
  to = "/videos.html"
  status = 301
  force = true
